apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2023-08-04T20:38:23Z
  generation: 1
  labels:
    run: giropops3
  name: giropops3
  namespace: default
  resourceVersion: "2811"
  uid: 813b7e02-addd-47df-8f93-35ec677b0a96
spec:
  replicas: 1
  selector:
    run: giropops2
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: giropops2
    spec:
      containers:
      - args:
        - dry-run=client
        image: nginx
        imagePullPolicy: Always
        name: giropops2
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status:
  replicas: 0
